GET http://localhost:5000/mdproAdmin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJNdWhhbW1hZCBSaXpraSBBa2JhciIsImVtYWlsIjoibWRwcm9hZG1pbkBnbWFpbC5jb20iLCJpYXQiOjE2NTYwMDk2OTIsImV4cCI6MTY1NjAwOTcxMn0.qUQmRyVaTjZFGcrP7oKIFOfFNwW5F88n5PeSbvzNId4


# ###
# POST http://localhost:5000/mdproAdmin
# Content-Type: application/json

# {
#     "name" : "Muhammad Rizki Akbar",
#     "email" : "mdproadmin@gmail.com",
#     "password" : "mdproadmin",
#     "confPassword" : "mdproadmin1",
#     "image" : "1.jpg",
#     "url" : "17200037@bsi.ac.id",
#     "gender": "laki-laki"
# }


###
POST http://localhost:5000/mdprologin
Content-Type: application/json

{
    "email" : "mdproadmin@gmail.com",
    "password" : "mdproadmin"
}



###
GET http://localhost:5000/mdprotoken


###
DELETE http://localhost:5000/mdprologout

